In [2]:
import torch
import torch.nn as nn
max_sequence_length = 10
d_model = 6

<math xmlns="http://www.w3.org/1998/Math/MathML" display="block">
  <mi>P</mi>
  <mi>E</mi>
  <mo stretchy="false">(</mo>
  <mtext>position</mtext>
  <mo>,</mo>
  <mn>2</mn>
  <mi>i</mi>
  <mo stretchy="false">)</mo>
  <mo>=</mo>
  <mi>sin</mi>
  <mo data-mjx-texclass="NONE">&#x2061;</mo>
  <mrow data-mjx-texclass="ORD">
    <mo minsize="2.047em" maxsize="2.047em">(</mo>
  </mrow>
  <mfrac>
    <mtext>position</mtext>
    <msup>
      <mn>10000</mn>
      <mfrac>
        <mrow>
          <mn>2</mn>
          <mi>i</mi>
        </mrow>
        <msub>
          <mi>d</mi>
          <mrow data-mjx-texclass="ORD">
            <mi>m</mi>
            <mi>o</mi>
            <mi>d</mi>
            <mi>e</mi>
            <mi>l</mi>
          </mrow>
        </msub>
      </mfrac>
    </msup>
  </mfrac>
  <mrow data-mjx-texclass="ORD">
    <mo minsize="2.047em" maxsize="2.047em">)</mo>
  </mrow>
</math>

<math xmlns="http://www.w3.org/1998/Math/MathML" display="block">
  <mi>P</mi>
  <mi>E</mi>
  <mo stretchy="false">(</mo>
  <mtext>position</mtext>
  <mo>,</mo>
  <mn>2</mn>
  <mi>i</mi>
  <mo>+</mo>
  <mn>1</mn>
  <mo stretchy="false">)</mo>
  <mo>=</mo>
  <mi>cos</mi>
  <mo data-mjx-texclass="NONE">&#x2061;</mo>
  <mrow data-mjx-texclass="ORD">
    <mo minsize="2.047em" maxsize="2.047em">(</mo>
  </mrow>
  <mfrac>
    <mtext>position</mtext>
    <msup>
      <mn>10000</mn>
      <mfrac>
        <mrow>
          <mn>2</mn>
          <mi>i</mi>
        </mrow>
        <msub>
          <mi>d</mi>
          <mrow data-mjx-texclass="ORD">
            <mi>m</mi>
            <mi>o</mi>
            <mi>d</mi>
            <mi>e</mi>
            <mi>l</mi>
          </mrow>
        </msub>
      </mfrac>
    </msup>
  </mfrac>
  <mrow data-mjx-texclass="ORD">
    <mo minsize="2.047em" maxsize="2.047em">)</mo>
  </mrow>
</math>

We can re-write them as

<math xmlns="http://www.w3.org/1998/Math/MathML" display="block">
  <mi>P</mi>
  <mi>E</mi>
  <mo stretchy="false">(</mo>
  <mtext>position</mtext>
  <mo>,</mo>
  <mn>2</mn>
  <mi>i</mi>
  <mo>+</mo>
  <mn>1</mn>
  <mo stretchy="false">)</mo>
  <mo>=</mo>
  <mi>cos</mi>
  <mo data-mjx-texclass="NONE">&#x2061;</mo>
  <mrow data-mjx-texclass="ORD">
    <mo minsize="2.047em" maxsize="2.047em">(</mo>
  </mrow>
  <mfrac>
    <mtext>position</mtext>
    <msup>
      <mn>10000</mn>
      <mfrac>
        <mrow>
          <mn>2</mn>
          <mi>i</mi>
        </mrow>
        <msub>
          <mi>d</mi>
          <mrow data-mjx-texclass="ORD">
            <mi>m</mi>
            <mi>o</mi>
            <mi>d</mi>
            <mi>e</mi>
            <mi>l</mi>
          </mrow>
        </msub>
      </mfrac>
    </msup>
  </mfrac>
  <mrow data-mjx-texclass="ORD">
    <mo minsize="2.047em" maxsize="2.047em">)</mo>
  </mrow>
</math>

when i is even

<math xmlns="http://www.w3.org/1998/Math/MathML" display="block">
  <mi>P</mi>
  <mi>E</mi>
  <mo stretchy="false">(</mo>
  <mtext>position</mtext>
  <mo>,</mo>
  <mn>2</mn>
  <mi>i</mi>
  <mo>+</mo>
  <mn>1</mn>
  <mo stretchy="false">)</mo>
  <mo>=</mo>
  <mi>cos</mi>
  <mo data-mjx-texclass="NONE">&#x2061;</mo>
  <mrow data-mjx-texclass="ORD">
    <mo minsize="2.047em" maxsize="2.047em">(</mo>
  </mrow>
  <mfrac>
    <mtext>position</mtext>
    <msup>
      <mn>10000</mn>
      <mfrac>
        <mrow>
          <mn>2</mn>
          <mi>i</mi>
        </mrow>
        <msub>
          <mi>d</mi>
          <mrow data-mjx-texclass="ORD">
            <mi>m</mi>
            <mi>o</mi>
            <mi>d</mi>
            <mi>e</mi>
            <mi>l</mi>
          </mrow>
        </msub>
      </mfrac>
    </msup>
  </mfrac>
  <mrow data-mjx-texclass="ORD">
    <mo minsize="2.047em" maxsize="2.047em">)</mo>
  </mrow>
</math>
when i is odd

In [3]:
even_i = torch.arange(0, d_model, 2).float()
print(even_i)

even_denominator = torch.pow(10000, even_i / d_model)
print(even_denominator)

odd_i = torch.arange(1, d_model, 2).float()
print(odd_i)

odd_dominator = torch.pow(10000, (odd_i - 1) / d_model)
print(odd_dominator)

print(even_denominator == odd_dominator)

denominator = even_denominator
position = torch.arange(max_sequence_length, dtype = torch.float).reshape(max_sequence_length, 1)
print(position)

even_PE = torch.sin(position / denominator)
odd_PE = torch.cos(position / denominator) 

tensor([0., 2., 4.])
tensor([  1.0000,  21.5443, 464.1590])
tensor([1., 3., 5.])
tensor([  1.0000,  21.5443, 464.1590])
tensor([True, True, True])
tensor([[0.],
        [1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])


In [4]:
even_PE, even_PE.shape, odd_PE, odd_PE.shape

(tensor([[ 0.0000,  0.0000,  0.0000],
         [ 0.8415,  0.0464,  0.0022],
         [ 0.9093,  0.0927,  0.0043],
         [ 0.1411,  0.1388,  0.0065],
         [-0.7568,  0.1846,  0.0086],
         [-0.9589,  0.2300,  0.0108],
         [-0.2794,  0.2749,  0.0129],
         [ 0.6570,  0.3192,  0.0151],
         [ 0.9894,  0.3629,  0.0172],
         [ 0.4121,  0.4057,  0.0194]]),
 torch.Size([10, 3]),
 tensor([[ 1.0000,  1.0000,  1.0000],
         [ 0.5403,  0.9989,  1.0000],
         [-0.4161,  0.9957,  1.0000],
         [-0.9900,  0.9903,  1.0000],
         [-0.6536,  0.9828,  1.0000],
         [ 0.2837,  0.9732,  0.9999],
         [ 0.9602,  0.9615,  0.9999],
         [ 0.7539,  0.9477,  0.9999],
         [-0.1455,  0.9318,  0.9999],
         [-0.9111,  0.9140,  0.9998]]),
 torch.Size([10, 3]))

In [6]:
stacked = torch.stack([even_PE, odd_PE], dim=2)
print(stacked.shape)
PE = torch.flatten(stacked, start_dim=1, end_dim=2)
PE, PE.shape

torch.Size([10, 3, 2])


(tensor([[ 0.0000,  1.0000,  0.0000,  1.0000,  0.0000,  1.0000],
         [ 0.8415,  0.5403,  0.0464,  0.9989,  0.0022,  1.0000],
         [ 0.9093, -0.4161,  0.0927,  0.9957,  0.0043,  1.0000],
         [ 0.1411, -0.9900,  0.1388,  0.9903,  0.0065,  1.0000],
         [-0.7568, -0.6536,  0.1846,  0.9828,  0.0086,  1.0000],
         [-0.9589,  0.2837,  0.2300,  0.9732,  0.0108,  0.9999],
         [-0.2794,  0.9602,  0.2749,  0.9615,  0.0129,  0.9999],
         [ 0.6570,  0.7539,  0.3192,  0.9477,  0.0151,  0.9999],
         [ 0.9894, -0.1455,  0.3629,  0.9318,  0.0172,  0.9999],
         [ 0.4121, -0.9111,  0.4057,  0.9140,  0.0194,  0.9998]]),
 torch.Size([10, 6]))

In [7]:


import torch
import torch.nn as nn

class PositionalEncoding(nn.Module):

    def __init__(self, d_model, max_sequence_length):
        super().__init__()
        self.max_sequence_length = max_sequence_length
        self.d_model = d_model

    def forward(self):
        even_i = torch.arange(0, self.d_model, 2).float()
        denominator = torch.pow(10000, even_i/self.d_model)
        position = torch.arange(self.max_sequence_length).reshape(self.max_sequence_length, 1)
        even_PE = torch.sin(position / denominator)
        odd_PE = torch.cos(position / denominator)
        stacked = torch.stack([even_PE, odd_PE], dim=2)
        PE = torch.flatten(stacked, start_dim=1, end_dim=2)
        return PE
     

pe = PositionalEncoding(d_model=6, max_sequence_length=10)
pe.forward()
     


tensor([[ 0.0000,  1.0000,  0.0000,  1.0000,  0.0000,  1.0000],
        [ 0.8415,  0.5403,  0.0464,  0.9989,  0.0022,  1.0000],
        [ 0.9093, -0.4161,  0.0927,  0.9957,  0.0043,  1.0000],
        [ 0.1411, -0.9900,  0.1388,  0.9903,  0.0065,  1.0000],
        [-0.7568, -0.6536,  0.1846,  0.9828,  0.0086,  1.0000],
        [-0.9589,  0.2837,  0.2300,  0.9732,  0.0108,  0.9999],
        [-0.2794,  0.9602,  0.2749,  0.9615,  0.0129,  0.9999],
        [ 0.6570,  0.7539,  0.3192,  0.9477,  0.0151,  0.9999],
        [ 0.9894, -0.1455,  0.3629,  0.9318,  0.0172,  0.9999],
        [ 0.4121, -0.9111,  0.4057,  0.9140,  0.0194,  0.9998]])